language:
    - c
sudo:
    - required

before_install:
    - sudo apt-get update

install:
    - sudo apt install doxygen ninja-build

script:
    - mkdir build && cd build
    - cmake .. -GNinja -DBUILDDOC=1 && ninja -j4 && ninja doc
